name: powerfitness
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
version: 1.0.0+1

environment:
  sdk: ^3.11.5

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  get: ^4.7.3
  http: ^1.6.0
  google_fonts: ^6.2.1
  flutter_svg: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints.
  flutter_lints: ^6.0.0

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is included.
  uses-material-design: true

  # To add assets to your application, add an assets section.
  assets:
    - assets/images/
    - assets/icons/

  # To add custom fonts to your application, add a fonts section here.
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700

    - family: Rajdhani
      fonts:
        - asset: assets/fonts/Rajdhani/Rajdhani-Regular.ttf
        - asset: assets/fonts/Rajdhani/Rajdhani-Medium.ttf
          weight: 500
        - asset: assets/fonts/Rajdhani/Rajdhani-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Rajdhani/Rajdhani-Bold.ttf
          weight: 700

    - family: LeagueSpartan
      fonts:
        - asset: assets/fonts/League_Spartan/LeagueSpartan-VariableFont_wght.ttf
